// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_game_match_ from "./routes/[game]/[match].tsx";
import * as $_game_index from "./routes/[game]/index.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $AssignPlayers from "./islands/AssignPlayers.tsx";
import * as $CreateMatchButton from "./islands/CreateMatchButton.tsx";
import * as $JoinMatchButton from "./islands/JoinMatchButton.tsx";
import * as $LeaveMatchButton from "./islands/LeaveMatchButton.tsx";
import * as $LoadingSpinner from "./islands/LoadingSpinner.tsx";
import * as $LobbyBrowser from "./islands/LobbyBrowser.tsx";
import * as $MatchClient from "./islands/MatchClient.tsx";
import * as $NoThanksClient from "./islands/NoThanksClient.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[game]/[match].tsx": $_game_match_,
    "./routes/[game]/index.tsx": $_game_index,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AssignPlayers.tsx": $AssignPlayers,
    "./islands/CreateMatchButton.tsx": $CreateMatchButton,
    "./islands/JoinMatchButton.tsx": $JoinMatchButton,
    "./islands/LeaveMatchButton.tsx": $LeaveMatchButton,
    "./islands/LoadingSpinner.tsx": $LoadingSpinner,
    "./islands/LobbyBrowser.tsx": $LobbyBrowser,
    "./islands/MatchClient.tsx": $MatchClient,
    "./islands/NoThanksClient.tsx": $NoThanksClient,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
